### ISSUE TITLE
Non Compliant Repo Structure

### ISSUE THREAD

**Issue by DBurgers** [roopesh/ad-qolsys#11]
When attempting to add the repo as a custom integration I get the error "Repostitory structure for 1.7.1 is not compliant"

**System Health**
Version | core-2021.4.6
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.8.0-50-generic
CPU Architecture | x86_64
Timezone | America/Chicago

**Home Assistant Community Store**
GitHub API | ok
Github API Calls Remaining | 4401
Installed Version | 1.11.3
Stage | running
Available Repositories | 776
Installed Repositories | 6

**Home Assistant Supervisor**
Host Operating System | Ubuntu 20.10
Update Channel | stable
Supervisor Version | supervisor-2021.04.0
Docker Version | 20.10.6
Disk Total | 218.6 GB
Disk Used | 28.4 GB
Healthy | true
Supported | Unsupported – more info
Supervisor API | ok
Version API | ok
Installed Add-ons | Node-RED (9.0.1), File editor (5.2.0), AppDaemon 4 (0.6.0)

**Comment by roopesh** [comment]
Please read the thread:

https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405/180?u=crazeeeyez

https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405/154?u=crazeeeyez
