### ISSUE TITLE
Make Night mode configurable

### ISSUE THREAD

**Issue by ifeign** [roopesh/ad-qolsys#17]
This plugin has been working great, my primary use is to pass my Qolsys system into HomeKit. Unfortunately, this creates an alarm accessory that comes with 4 modes, 3 of which work perfectly. Night mode does nothing. In the past with an old Homebridge plugin, night mode on my ADC panel was the same as Home. It would be great if we could set this as an option. Bonus would be to be able to specify entry delay, so Night could be something like Home + no entry delay

**Comment by roopesh** [comment]
Try 1.8.1.  Night mode now maps to stay.

**Comment by ifeign** [comment]
Just tested, works perfectly. Thank you!
