### ISSUE TITLE
Other zone types

### ISSUE THREAD

**Issue by mzac** [roopesh/ad-qolsys#2]
As mentioned in the forum, I have other zone types:

```
{
    "id": "xxx",
    "type": "GlassBreak",
    "name": "Kitchen Glass Break",
    "group": "glassbreak",
    "status": "Closed",
    "state": "0",
    "zone_id": 4,
    "zone_physical_type": 12,
    "zone_alarm_type": 0,
    "zone_type": 19,
    "partition_id": 0
},
{
    "id": "xxx",
    "type": "SmokeDetector",
    "name": "Basement Smoke Detector",
    "group": "smoke_heat",
    "status": "Closed",
    "state": "0",
    "zone_id": 5,
    "zone_physical_type": 9,
    "zone_alarm_type": 9,
    "zone_type": 5,
    "partition_id": 0
},
{
    "id": "xxx",
    "type": "Motion",
    "name": "Upstairs Motion Detector",
    "group": "awayinstantmotion",
    "status": "Closed",
    "state": "0",
    "zone_id": 8,
    "zone_physical_type": 2,
    "zone_alarm_type": 3,
    "zone_type": 2,
    "partition_id": 0
},
{
    "id": "xxx",
    "type": "Water",
    "name": "Water",
    "group": "WaterSensor",
    "status": "Closed",
    "state": "0",
    "zone_id": 14,
    "zone_physical_type": 8,
    "zone_alarm_type": 0,
    "zone_type": 15,
    "partition_id": 0
}
```

**Comment by mzac** [comment]
You mean when the zones are triggered?  I'll check but they are probably all binary sensors that just give an open/closed message.

**Comment by roopesh** [comment]
If they're binary sensors, which kinds? https://www.home-assistant.io/integrations/binary_sensor/#device-class

SmokeDetector: smoke - closed=off, open=on
GlassBreak??: safety - closed=off, open=on
Motion: motion - closed=off (no motion), open=on (motion)
Water: moisture - closed=off (no leak), open=on (leak)

I could try these if you want to test for me.  I don't have any of these types.

**Comment by mzac** [comment]
> If they're binary sensors, which kinds? https://www.home-assistant.io/integrations/binary_sensor/#device-class
> 
> SmokeDetector: smoke - closed=off, open=on
> GlassBreak??: safety - closed=off, open=on
> Motion: motion - closed=off (no motion), open=on (motion)
> Water: moisture - closed=off (no leak), open=on (leak)
> 
> I could try these if you want to test for me. I don't have any of these types.

Yep, that looks right!  As you saw above they are all showing 'closed' which means they are in the normal state.  For Glass break, safety sounds like the right option.

**Comment by roopesh** [comment]
Try this off the more-sensors branch: https://github.com/roopesh/ad-qolsys/blob/More-sensors/apps/ad-qolsys/qolsys_requests.py.  Replace the file and restart appdaemon.  Let me know if they are right when triggered.

**Comment by mzac** [comment]
> Try this off the more-sensors branch: https://github.com/roopesh/ad-qolsys/blob/More-sensors/apps/ad-qolsys/qolsys_requests.py. Replace the file and restart appdaemon. Let me know if they are right when triggered.

Trying now.  I'm guessing every time you update a file that is part of hacs/appdaemon you need to restart appdaemon?

**Comment by mzac** [comment]
I would say it looks good!

![image](https://user-images.githubusercontent.com/10270879/114089987-d6b19780-9884-11eb-934a-e257ea7b8260.png)
