### ISSUE TITLE
Change info message to be retained

### ISSUE THREAD

**Issue by mzac** [roopesh/ad-qolsys#6]
I notice that when I restart Home Assistant all the entities disappear and I need to re-start AppDaemon to get them back.

Could the message that sends the info, ie the config of the entities be set with a retain flag in mqtt?

**Comment by roopesh** [comment]
Thinking about this... I don't think the info needs to be retained.  Each mqtt config and state message needs to be retained.  Still thinking.

**Comment by smwoodward** [comment]
@roopesh what are some ways you would like the availability tested?

**Comment by roopesh** [comment]
1. Shutdown AppDaemon (AD) while HA was still running.  Alarm control panel (ACP) and binary sensors (BS) become Unavailable (but still exist).
2. Restart HA while AD is running.  All sensors come back online as expected with the last state of the sensors and panel.
3. Shutdown HA and AD.  ACP and BS come back as unavailable until AD is started.

**Comment by smwoodward** [comment]
I will confirm that it does work. Shutting down AD and the devices become unavailable, restarting HA the entities stay and show unavailable, and restarting AD they come back from unavailable.

**Comment by roopesh** [comment]
@smwoodward I think you had some use cases with HomeKit and customizing entities as well.

**Comment by smwoodward** [comment]
@roopesh correct. The entities do stay passed into HomeKit and show as "no response" if AD is shut down.
